#!/usr/bin/env python3
"""Check that every exported C/C++ function has a Python sys binding.

The check intentionally reuses `tools/find_exports.py` so the export list is
always derived from the same source of truth as the build.
"""

from __future__ import annotations

import re
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RM_LINES_SRC = ROOT / "rm_lines"
SYS_BINDINGS = ROOT / "rm_lines_sys" / "src" / "rm_lines_sys" / "__init__.py"
FIND_EXPORTS = ROOT / "tools" / "find_exports.py"
IGNORED_EXPORTS = {"setDebugLogger", "setErrorLogger", "setLogger"}


def run_find_exports() -> tuple[str, str]:
    with tempfile.TemporaryDirectory(prefix="rm_lines_exports_") as tmpdir:
        tmp_path = Path(tmpdir)
        subprocess.run(
            [sys.executable, str(FIND_EXPORTS), str(RM_LINES_SRC)],
            cwd=tmp_path,
            check=True,
        )

        exports = tmp_path / "exports.txt"
        exported_functions = tmp_path / "exported_functions.txt"

        if not exports.exists():
            raise FileNotFoundError(
                f"{exports} was not generated by find_exports.py"
            )
        if not exported_functions.exists():
            raise FileNotFoundError(
                f"{exported_functions} was not generated by find_exports.py"
            )

        return exports.read_text(), exported_functions.read_text()


def read_export_names(exports_text: str) -> set[str]:
    return {
        line.strip()
        for line in exports_text.splitlines()
        if line.strip() and line.strip() not in IGNORED_EXPORTS
    }


def read_sys_annotation_names() -> set[str]:
    text = SYS_BINDINGS.read_text(errors="ignore")
    # Methods in `LibAnnotations` are defined as `def name(self, ...)` with a
    # 4-space indent.
    return {
        name
        for name in re.findall(
            r"^\s{4}def\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(", text, re.MULTILINE
        )
        if name not in IGNORED_EXPORTS
    }


def read_sys_binding_names() -> set[str]:
    text = SYS_BINDINGS.read_text(errors="ignore")
    # `_lib.<name>.argtypes/restype = ...` definitions.
    return {
        name
        for name in re.findall(r"^\s*_lib\.([A-Za-z_][A-Za-z0-9_]*)\.", text, re.MULTILINE)
        if name not in IGNORED_EXPORTS
    }


def main() -> int:
    exports_text, _exported_functions_text = run_find_exports()

    exports = read_export_names(exports_text)
    annotations = read_sys_annotation_names()
    bindings = read_sys_binding_names()

    missing_annotations = sorted(exports - annotations)
    missing_bindings = sorted(exports - bindings)
    extra_annotations = sorted(annotations - exports)
    extra_bindings = sorted(bindings - exports)

    ok = True

    if missing_annotations:
        ok = False
        print(
            "Missing `rm_lines_sys` annotations for exported functions:",
            file=sys.stderr,
        )
        for name in missing_annotations:
            print(f"  - {name}", file=sys.stderr)

    if missing_bindings:
        ok = False
        print(
            "Missing `rm_lines_sys` `_lib.<name>` bindings for exported functions:",
            file=sys.stderr,
        )
        for name in missing_bindings:
            print(f"  - {name}", file=sys.stderr)

    if extra_annotations:
        print(
            "Warning: `rm_lines_sys` annotations exist for non-exported names:",
            file=sys.stderr,
        )
        for name in extra_annotations:
            print(f"  - {name}", file=sys.stderr)

    if extra_bindings:
        print(
            "Warning: `rm_lines_sys` bindings exist for non-exported names:",
            file=sys.stderr,
        )
        for name in extra_bindings:
            print(f"  - {name}", file=sys.stderr)

    if ok:
        print(
            f"OK: {len(exports)} exports matched against annotations and bindings."
        )
        return 0

    return 1


if __name__ == "__main__":
    raise SystemExit(main())
