# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms and publish to PYPI

on:
  push:
    tags: [ "*" ]
    branches-ignore: [ "main" ]
    paths:
      - 'CMakeLists.txt'
      - '.github/workflows/build.yml'
      - 'tests/**'
      - 'rm_lines/**'
      - 'rm_lines_sys/**'
      - 'requirements.txt'
      - 'tools/**'
  pull_request:
    branches: [ "main", "experimental" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-sys:
    name: ${{ matrix.runner }} ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write
    # Skip the `latest-draft` tag to prevent recursive runs
    if: github.ref_name != 'latest-draft'

    strategy:
      fail-fast: true
      matrix:
        include:
          - os: 'ubuntu'
            runner: 'ubuntu-latest'
            target: 'x86_64-unknown-linux-gnu'
            cpp_compiler: 'g++'
            c_compiler: 'gcc'
            python_version: '3.9'
            python_arch: 'x64'
            build_type: 'Release'
            run_tests: true
            build_wheel: true
          - os: 'windows'
            runner: 'windows-latest'
            target: 'x86_64-pc-windows-msvc'
            cmake_platform: 'x64'
            python_version: '3.9'
            python_arch: 'x64'
            build_type: 'Release'
            run_tests: true
            build_wheel: true
          - os: 'windows'
            runner: 'windows-11-arm'
            target: 'aarch64-pc-windows-msvc'
            cmake_platform: 'ARM64'
            python_version: '3.12'
            python_arch: 'arm64'
            build_type: 'Release'
            run_tests: true
            build_wheel: true
          - os: 'macos'
            runner: 'macos-13'
            target: 'x86_64-apple-darwin'
            cpp_compiler: 'clang++'
            c_compiler: 'clang'
            python_version: '3.9'
            python_arch: 'x64'
            build_type: 'Release'
            run_tests: true
            build_wheel: true
    steps:
      - uses: actions/checkout@v6

      - name: Fetch tags for current commit
        run: git fetch --tags --depth=1

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache CMake build files
        uses: actions/cache@v6
        with:
          path: ${{ steps.strings.outputs.build-output-dir }}
          key: ${{ runner.os }}-${{ matrix.target }}-cmake-${{ matrix.cpp_compiler || matrix.cmake_platform }}-${{ matrix.c_compiler || matrix.cmake_platform }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-cmake-${{ matrix.cpp_compiler || matrix.cmake_platform }}-${{ matrix.c_compiler || matrix.cmake_platform }}-

      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -A ${{ matrix.cmake_platform }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Configure CMake (Unix)
        if: runner.os != 'Windows'
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Build
        # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} --target rm_lines

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python_version }}
          architecture: ${{ matrix.python_arch }}
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry colorama Pillow

      - name: Update version
        shell: bash
        run: |
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            # Check if there is a tag on the current commit
            tag=$(git tag --points-at HEAD | head -n 1)
            if [[ -n "$tag" ]]; then
              echo "Tag found: $tag"
              version="${tag}"
            else
              echo "Failed to get tag, using dev"
              version="0.0.0.dev"
            fi
          else
            echo "Not on tagged commit, using dev"
            version="0.0.0.dev"
          fi
          echo "Version: $version"
          echo "version=${version}" >> "$GITHUB_ENV"
          sed -i -e "s|0.0.0+replaced-by-ci|${version}|g" rm_lines_sys/pyproject.toml

      - name: Run test & copy shared library to sys
        if: matrix.run_tests
        shell: bash
        run: |
          cd tests
          python test.py

      - name: Check sys bindings match exports
        shell: bash
        run: |
          python tools/check_sys_exports.py

      - name: Build with poetry
        if: matrix.build_wheel
        shell: bash
        run: |
          cd rm_lines_sys
          poetry build -f wheel

      - name: Gather files into temp dir
        shell: bash
        run: |
          mkdir -p artifact
          if [[ "${{ matrix.build_wheel }}" == "true" ]]; then
            mv rm_lines_sys/dist/*.whl artifact/
          fi
          
          case "${{ matrix.os }}" in
            ubuntu*)
              mv "${{ steps.strings.outputs.build-output-dir }}/librm_lines.so" artifact/
              ;;
            macos*)
              mv "${{ steps.strings.outputs.build-output-dir }}/librm_lines.dylib" artifact/
              ;;
            windows*)
              mv "${{ steps.strings.outputs.build-output-dir }}/${{ matrix.build_type }}/rm_lines.dll" artifact/
              ;;
          esac

      - name: Rename wheel to be Python-agnostic
        if: matrix.build_wheel
        shell: bash
        run: |
          file=$(ls artifact/*.whl)
          new_name=$(python -c "import sys, re; print(re.sub(r'cp3\d+-cp3\d+', 'py3-none', sys.argv[1]))" "$file")
          mv "$file" "$new_name"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.runner }}-${{ matrix.target }}
          path: |
            artifact/*.whl
            artifact/librm_lines.so
            artifact/librm_lines.dylib
            artifact/rm_lines.dll
          retention-days: 5

      - uses: rickstaa/action-create-tag@v1
        if: matrix.runner == 'ubuntu-latest'
        with:
          tag: latest-draft
          force_push_tag: true

  create-draft-release:
    name: Create Draft Release
    needs: build-sys
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v6
        with:
          path: artifacts/

      - name: Create Draft Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest-draft
          body: "Ref: ${{ github.ref_name }}."
          name: Lib rMLines Draft Release
          files: artifacts/**/*
          prerelease: true

  publish-to-pypi:
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
      - build-sys
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/rm_lines_sys
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v6
        with:
          path: artifacts/
      - name: Move wheels to dist
        shell: bash
        run: |
          mkdir -p dist
          find artifacts -type f -name "*.whl" -exec mv {} dist/ \;
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
